import {
  Backpack,
  BarChart3,
  BookOpen,
  Boxes,
  CircleDollarSign,
  FileText,
  LayoutDashboard,
  Package,
  Palette,
  PackageSearch,
  PenTool,
  ShoppingCart,
  Star,
  Truck,
  Users2,
} from "lucide-react";

export const storeNavigation = [
  { label: "Accueil", href: "/" },
  { label: "Catalogue", href: "/catalog" },
  { label: "Rayons", href: "/categories" },
  { label: "Packs", href: "/categories/packs-grossiste" },
  { label: "Rentree", href: "/categories/fournitures-scolaires" },
];

export const storeShortcutNavigation = [
  { label: "Cartables", href: "/categories/bagagerie", icon: Backpack },
  { label: "Stylos", href: "/categories/fournitures-scolaires", icon: PenTool },
  { label: "Cahiers", href: "/categories/papier-impression", icon: BookOpen },
  { label: "Trousses", href: "/categories/bagagerie", icon: Package },
  { label: "Creatif", href: "/categories/arts-creatifs", icon: Palette },
  { label: "Bons plans", href: "/categories/packs-grossiste", icon: Star },
];

export const dashboardNavigation = [
  { label: "Vue d'ensemble", href: "/admin", icon: LayoutDashboard, section: "Pilotage" },
  { label: "Produits", href: "/admin/products", icon: PackageSearch, section: "Catalogue" },
  { label: "Categories", href: "/admin/categories", icon: Boxes, section: "Catalogue" },
  { label: "Stock", href: "/admin/inventory", icon: Boxes, section: "Operations" },
  { label: "Commandes", href: "/admin/orders", icon: ShoppingCart, section: "Operations" },
  { label: "Livraisons", href: "/admin/deliveries", icon: Truck, section: "Operations" },
  { label: "Factures", href: "/admin/invoices", icon: FileText, section: "Operations" },
  { label: "Clients", href: "/admin/customers", icon: Users2, section: "Relations" },
  { label: "Fournisseurs", href: "/admin/suppliers", icon: Truck, section: "Relations" },
  { label: "Finance", href: "/admin/finance", icon: CircleDollarSign, section: "Proprietaire", ownerOnly: true },
  { label: "Rapports", href: "/admin/reports", icon: BarChart3, section: "Proprietaire", ownerOnly: true },
];

export const tunisianGovernorates = [
  "Ariana",
  "Beja",
  "Ben Arous",
  "Bizerte",
  "Gabes",
  "Gafsa",
  "Jendouba",
  "Kairouan",
  "Kasserine",
  "Kebili",
  "Kef",
  "Mahdia",
  "Manouba",
  "Medenine",
  "Monastir",
  "Nabeul",
  "Sfax",
  "Sidi Bouzid",
  "Siliana",
  "Sousse",
  "Tataouine",
  "Tozeur",
  "Tunis",
  "Zaghouan",
];
